- name: generate master configuration for kubeadm init
  template:
    src: master_config_v1.12.yml.tpl
    dest: /root/master_config.yml
    owner: root
    group: root
    mode: 0664

- name: init master node
  shell: kubeadm init --config /root/master_config.yml

- name: create .kube dir
  shell: mkdir -p /root/.kube

- name: copy kubeconfig file
  shell: cp -i /etc/kubernetes/admin.conf /root/.kube/config

- name: install calico rbac
  shell: kubectl apply -f https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml

- name: install calico
  shell: kubectl apply -f https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
