- name: create kubeadm dir
  file:
    path: "{{ kube_kubeadm_dir }}"
    state: directory

- name: copy kubeadm config
  template:
    src: kubeadmcfg_worker.yaml.tpl
    dest: "{{ kube_kubeadm_worker_config }}"

- name: add worker to cluster
  shell: "kubeadm join --config={{ kube_kubeadm_worker_config }}"
